### ISSUE TITLE
SyntaxError on import

### ISSUE THREAD

**Issue by jongmana** [zazuko/openlayers-elements#10]
I'm getting a SyntaxError when I import the 'ol-map'.
`Uncaught SyntaxError: The requested module '../../rbush/index.js' does not provide an export named 'default'`

**Comment by tpluscode** [comment]
Unfortunately, even though OpenLayers itself is built with ES6 modules, its dependency [rbush](https://www.npmjs.com/package/rbush) is using commonjs.

For that reason `@openlayers-elements/map` must be bundled using webpack, rollup or similar.

**Comment by tpluscode** [comment]
Closing for now. Please let me know if you need any more help. You may also have a look at the webpack setup in [`demos` folder](https://github.com/zazuko/openlayers-elements/tree/master/demos)
