### ISSUE TITLE
How to cluster markers

### ISSUE THREAD

**Issue by amitaibu** [zazuko/openlayers-elements#32]
Is it possible to cluster markers as done here - https://openlayers.org/en/latest/examples/cluster.html ?

**Comment by tpluscode** [comment]
No, it's not currently possible, at least not with declarative API. To be honest I don't understand this feature. I've never used it before and I wouldn't have an idea for the "web components" way for implementing this.

That said, you can extend the base vector layer element to do your bidding. See the [GeoJSON element](https://github.com/zazuko/openlayers-elements/blob/master/elements/openlayers-elements/ol-layer-geojson.ts) as example. All you would need for starters is implement `_createSource` to return a `Cluster`. [Styling is also supported](https://github.com/zazuko/openlayers-elements/blob/master/elements/openlayers-core/ol-layer-vector.ts#L45)

Let me know if can help you some more.

**Comment by amitaibu** [comment]
Thanks :+1:
