### ISSUE TITLE
Markers on Map

### ISSUE THREAD

**Issue by semanticfire** [zazuko/openlayers-elements#4]
I would be interested in having a method of putting markers on the map, preferably configurable icons and click actions.

**Comment by semanticfire** [comment]
including a way of zooming to extent

**Comment by tpluscode** [comment]
Hey @semanticfire, do you have more specific requirements I mind?

I see that markers are bound to a layer, so I'd probably nest them under a layer element so that they are combined with that layer and added to the map.

Off the top of my head, when put together, it would be something like:

```html
<ol-map>
  <ol-layer-openstreetmap>
    <ol-marker-icon src="images/hotel.png" lat="20" lon="40" color="green" />
    <ol-marker-circle radius="2" lat="10" lon="80" stroke-color="red" fill-color="#FFF" />
  </ol-layer-openstreetmap>
</ol-map>
```

Granted, the wrapped JS API is much more rich then a declarative structure can convey. Let me know if this would be a good enough start for you.

**Comment by semanticfire** [comment]
In my specific use case the markers would be dynamic but the parameters seem like a good start.
You probably want to have a marker offset x/y as well for the marker icon.

slightly OT but would other elements be allowed within the map ?

```html
<ol-map>
  <ol-layer-openstreetmap>
    <property-shape path='lat,lon' bind='ol-marker-icon[lat],ol-marker-icon[lat]'>
       <ol-marker-icon src="images/hotel.png" color="green" />
    </property-shape>
    <ol-marker-circle radius="2" lat="10" lon="80" stroke-color="red" fill-color="#FFF" />
  </ol-layer-openstreetmap>
</ol-map>```

**Comment by tpluscode** [comment]
> In my specific use case the markers would be dynamic

It's not ye implemented but the map and all it's descendants will have to become reactive to prop/attribute changes. For example moving the marker around when the coordinates change. Is that you meant?

> You probably want to have a marker offset x/y as well for the marker icon.

Yes, definitely :+1:

> would other elements be allowed within the map ?

I don't quite understand the snippet. I cannot find a property shape in the OL API. What is the proposed semantics here?

**Comment by semanticfire** [comment]
> > In my specific use case the markers would be dynamic
> 
> It's not ye implemented but the map and all it's descendants will have to become reactive to prop/attribute changes. For example moving the marker around when the coordinates change. Is that you meant?
Nope I mean I want to add and remove markers through Javascript code
> 
> > would other elements be allowed within the map ?
> 
> I don't quite understand the snippet. I cannot find a property shape in the OL API. What is the proposed semantics here?

property-shape is a component we use to inject RDF into the UI through declaration, there was actually a error in my snippet:
```html
<ol-map>
  <ol-layer-openstreetmap>
    <property-shape path='geo:lat,geo:lon' bind='ol-marker-icon[lat],ol-marker-icon[lat]'>
       <ol-marker-icon src="images/hotel.png" color="green" />
    </property-shape>
    <ol-marker-circle radius="2" lat="10" lon="80" stroke-color="red" fill-color="#FFF" />
  </ol-layer-openstreetmap>
</ol-map>```

**Comment by tpluscode** [comment]
Oh, I understand now. 

The initial idea was to actually keep the structure without extra nesting. It would technically be possible to look for marker elements deep into layer's children but I think it will make the usage too unconstrained and potentially problematic for hypothetical future extensions.

---- 

About the property shape itself, does it have to be an element? It looks more like a templating extension. Does is produce multiple markers for multiple path matches? With `lit-html` it could be quite elegantly implemented as a directive:

```js
import propertyShape from 'somewhere'
import { html } from 'lit-html'

const path = 'geo:lat,geo:lon'

html`
<ol-map>
  <ol-layer-openstreetmap>
    ${propertyShape(graph, path, (lat, lon) => html`
        <ol-marker-icon .lat=${lat} .lon=${lon} src="images/hotel.png" color="green" />
    `)}
    <ol-marker-circle radius="2" lat="10" lon="80" stroke-color="red" fill-color="#FFF" />
  </ol-layer-openstreetmap>
</ol-map>`
`
```

**Comment by tpluscode** [comment]
I've added a basic icon marker functionality.

I'm thinking to make the deep search optional to enable your use case. Please consider that and let's track in a new issue if needed
