### ISSUE TITLE
Support for tiled web maps

### ISSUE THREAD

**Issue by semanticfire** [zazuko/openlayers-elements#5]
A layer component for Tiled Web Maps would be the next big wish, with the option to supply a array of hostnames

https://openlayers.org/en/latest/examples/xyz.html

**Comment by tpluscode** [comment]
Could you please elaborate on the `array of hostnames`?

**Comment by semanticfire** [comment]
in the XYZ Source you have the option to supply URI templates, which are basically the subdomains you can use in the URI
google use mt0 mt1 etc in the XYZ sources
see:
https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html

**Comment by tpluscode** [comment]
Ok. In the current state I simply defined the URL template as element property. So anything that is supported by OpenLayers will work.

```html
<ol-map zoom="7" lat="46.7985" lon="8.2318">
    <ol-layer-xyz url="http://c.tiles.wmflabs.org/hillshading/{z}/{x}/{y}.png"></ol-layer-xyz>
</ol-map>
```

There is but a single URL parameter. Would that be sufficient?

**Comment by semanticfire** [comment]
you would need to have a parameter which supports multiple values for the subdomain to make it work for e.g. google maps

**Comment by tpluscode** [comment]
Sure, I can expose the `urls` array too as input.

What I was referring to is this part of the docs:

> A {?-?} template pattern, for example subdomain{a-f}.domain.com, may be used instead of defining each one separately in the urls option.

I suppose that it caters for more typical use cases where the subdomain follows this pattern.

**Comment by semanticfire** [comment]
hmm, this part of the docs are a bit vague but I see what you mean
