### ISSUE TITLE
Please send events of changes caused by user interaction.

### ISSUE THREAD

**Issue by veith** [zazuko/openlayers-elements#63]
It would be very helpful / valuable if the component would send events about changes. 
**thank you!**

It would be very helpful / valuable if the component would send events about changes which are caused by user interaction.

i.e. a  **view-changed** event with `x, y, lat, lon, zoom, ...` would make the component directly usable as an input component.

**Comment by veith** [comment]
Reflecting the changes to the ol-map would be nice too.

**Comment by tpluscode** [comment]
Hello @veith. Thank you for your suggestions. I think I would approach this in two ways. 

First instances of `OlMap` have a set of their [native event](https://openlayers.org/en/latest/apidoc/module-ol_MapEvent-MapEvent.html), which I could simply forward from the `ol-map` element. For example, `moveend` could be used like

```html
<ol-map @on-moveend="${onMoveend}></ol-map>

<script>
  function onMoveend(event) {
    // The MapEvent provided in the detail object
    const rawEvent = event.detail
  }
</script>

The other idea is to provide a more targeted events, rewired from the native ones. The `view-changed` which you propose for one

**Comment by tpluscode** [comment]
Please see the demo built off PR #68: https://events--openlayers-elements.netlify.app/#/elements/ol-map/demos/demo/ol-map/

In the console you will see the `ol-map` log events `moveend` and `view-change`

> Reflecting the changes to the ol-map would be nice too.

I'm not sure how great we can make this. I added a `change` event, simply forwarded from the OpenLayers objects. Right now it will be fired by the map and layer elements.
