### ISSUE TITLE
Issues with attached events when combining with other custom elements.

### ISSUE THREAD

**Issue by justin0mcateer** [zazuko/openlayers-elements#76]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@openlayers-elements/core@0.2.1` for the project I'm working on.

When trying to wrap any of the elements into a different custom element, particularly between any of the parent child relationships, the elements throw an error on an unfulfilled 'attached' promise. This appears to be due to the default bubbling (or lack thereof) behavior for custom events. Setting the 'bubbles' and 'composed' properties when firing the attached elements resolves the issue for me and does not seem to affect the standard behavior.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@openlayers-elements/core/lib/events.js b/node_modules/@openlayers-elements/core/lib/events.js
index b477c93..b7653a4 100644
--- a/node_modules/@openlayers-elements/core/lib/events.js
+++ b/node_modules/@openlayers-elements/core/lib/events.js
@@ -2,6 +2,8 @@ export function forwardEvents(events, target, olObject) {
     for (const name of events) {
         olObject.on(name, (event) => {
             target.dispatchEvent(new CustomEvent(name, {
+                bubbles: true,
+                composed: true,
                 detail: event,
             }));
         });
diff --git a/node_modules/@openlayers-elements/core/mixins/Attachable.js b/node_modules/@openlayers-elements/core/mixins/Attachable.js
index ba5c09d..8728f8b 100644
--- a/node_modules/@openlayers-elements/core/mixins/Attachable.js
+++ b/node_modules/@openlayers-elements/core/mixins/Attachable.js
@@ -41,13 +41,13 @@ const AttachableMixin = function (Base, detailPropName) {
         }
         __attachToMap() {
             const detail = {};
-            this.dispatchEvent(new CustomEvent('attach', { detail }));
+            this.dispatchEvent(new CustomEvent('attach', { bubbles: true, composed: true, detail }));
             if (detailPropName in detail) {
                 this._attach(detail)
                     .then((detachFunc) => {
                     if (detachFunc) {
                         this.__detachFromMap = detachFunc;
-                        this.dispatchEvent(new Event('attached'));
+                        this.dispatchEvent(new Event('attached', { bubbles: true, composed: true }));
                     }
                 });
             }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tpluscode** [comment]
Thank you for reporting. I try to avoid bubbling+composed events but in this case they should be fine. Maybe I will only make sure that they are "terminated" at the map level as to prevent polluting the outer DOM

Curious though, how do you use the elements. By wrap you mean simply that they are inside other elements but no shadow DOM?

```html
<ol-map>
  <div>
    <ol-layer />
  </div>
</ol-map>
```

Or actually hidden inside another element

```html
<ol-map>
  <ex-element>
    <!-- shadow-root -->
      <ol-layer />
    <!-- /shadow-root -->
  </ex-element>
</ol-map>
```

**Comment by justin0mcateer** [comment]
The latter, inside another custom element, because I am using a controller tied to my state management to update features on the map layer and I do not want to re-render the whole map. There may be a better way that I am not aware of, as I am new to Web Components...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tpluscode** [comment]
Centralised state management is a good idea. However, you should not need it "only" to prevent unnecessary DOM manipulation.

For example, `lit-html` updates the DOM efficiently because it does not recreate the element tree on subsequent renders. See in this example, how every time the checkbox changes, the `renderMap` function is called and it switches the layer on top of the standard map: https://studio.webcomponents.dev/edit/Ba9MX0DIF8qrBCW6IKsc

If you look at the elements inspector, you will find that that lit-html does not remove and re-insert the `ol-map` itself, nor the bottom layer. They are only created in DOM once

**Comment by justin0mcateer** [comment]
The update has resolved the issues I had related to this. Thank you!
