### ISSUE TITLE
Lack of Type Definitions in NPM Package

### ISSUE THREAD

**Issue by justin0mcateer** [zazuko/openlayers-elements#82]
This is again, potentially my ignorance. However, the NPM package does not appear to include any type declarations. I am trying to subclass the OlLayerVector class and this is giving me some issues with TypeScript. 

Installing the package from a cloned and built local repository seems to address my issues. Given that this is a TypeScript native project, is there any reason to not include the declarations in the NPM package?

**Comment by tpluscode** [comment]
No reason, simply mistake, sorry. Will fix this today
